prod:
  .settings:
    no_script_name: true
    logging_enabled: true
dev:
  .settings:
    error_reporting: 32767
    web_debug: true
    cache: false
    no_script_name: false
    etag: false
test:
  .settings:
    error_reporting: 32759
    cache: false
    web_debug: false
    no_script_name: false
    etag: false
all:
  .settings:
    csrf_secret: 4b3198487854531b0d57125c19d0d072fa52ad40
    escaping_strategy: true
    escaping_method: ESC_SPECIALCHARS
    use_database: true
    check_lock: true
  .actions:
    login_module: default
    login_action: login
    secure_module: default
    secure_action: secure
    error_404_module: default
    error_404_action: error404
    module_disabled_module: default
    module_disabled_action: disabled
